# Generated by Django 4.0.1 on 2022-01-31 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_banco_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banco',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.banco'),
        ),
    ]
