# Generated by Django 4.0.1 on 2022-01-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_banco2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='banco2',
            new_name='banco',
        ),
    ]
